version: '3.8'

services:
  postgres:
    container_name: postgresql_database
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: arithmetic_operations
    volumes:
      - data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    build: .
    command: go run ./cmd/main.go
    container_name: go_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  data:
