version: '3.8'

services:
  postgres:
    container_name: daec_postgresql
    image: postgres
    ports:
      - "8100:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: arithmetic_operations
    networks:
      - app_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  orchestrator:
    restart: unless-stopped
    container_name: daec_orchestrator
    image: orchestrator:latest
    build:
      dockerfile: Dockerfile
    depends_on:
      - postgres
    network_mode: host

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge